<?xml version="1.0" encoding="utf-8"?><Database Name="appbookstore" Class="DataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\appbookstore.mdf;Integrated Security=True" SettingsObjectName="FINAL.Properties.Settings" SettingsPropertyName="appbookstoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Buku" Member="Bukus">
    <Type Name="Buku">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="kode_buku" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="nama_buku" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="harga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="thn_terbit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pengarang" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Penjualan" Member="Penjualans">
    <Type Name="Penjualan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_transaksi" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tanggal" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="judul_buku" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="jumlah" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>